name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    container:
      image: cualbondi/rust:1.37.0-0

    steps:
    - uses: actions/checkout@v1
    - name: Format
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy -- -D warnings -A clippy::ptr-arg
    - name: Tests
      run: cargo test --verbose
    - name: codecov
      run: taskset -c 0 cargo tarpaulin --out Xml && curl -s https://codecov.io/bash -o codecov.sh && bash codecov.sh
